/**
 * StorySection Component
 * Renders the chronological narrative chapters generated by Phase 4 AI engine.
 */

import { FadeReveal } from '../afterchat/FadeReveal';
import { Receipt } from './Receipt';
import { Story } from '../../types/story';
import { ChatMessage } from '../../types/chat';

interface StorySectionProps {
  story: Story | null;
  getMessagesByIds: (ids: string[]) => ChatMessage[];
  isUnlocked: boolean;
}

export function StorySection({ story, getMessagesByIds, isUnlocked }: StorySectionProps) {
  if (!story) {
    return (
      <section id="sec-story" className="report-story-section">
        <FadeReveal>
          <p className="eyebrow">03 · THE COMPLETE STORY</p>
          <h2>The narrative is generating...</h2>
        </FadeReveal>
      </section>
    );
  }

  // Preview mode shows first chapter only
  const displayChapters = isUnlocked ? story.chapters : story.chapters.slice(0, 1);

  return (
    <section id="sec-story" className="report-story-section">
      <FadeReveal>
        <p className="eyebrow">03 · THE COMPLETE STORY</p>
        <h2>{story.title}</h2>
        <p className="lede">{story.subtitle}</p>

        <div className="story-opening-box">
          <p className="story-opening-text">"{story.opening}"</p>
        </div>
      </FadeReveal>

      <div className="story-chapters-container">
        {displayChapters.map((chapter, idx) => (
          <FadeReveal key={chapter.id}>
            <article className="story-chapter-card">
              <div className="chapter-meta">
                <span className="chapter-num">CHAPTER {String(idx + 1).padStart(2, '0')}</span>
                <span className="chapter-period">{chapter.period}</span>
              </div>
              <h3 className="chapter-title">{chapter.title}</h3>
              <p className="chapter-narrative">{chapter.narrative}</p>

              {chapter.keyStats.length > 0 && (
                <div className="chapter-stats-row">
                  {chapter.keyStats.map((st) => (
                    <span key={st.label} className="chapter-stat-pill">
                      <b>{st.value}</b> {st.label}
                    </span>
                  ))}
                </div>
              )}

              {chapter.evidenceMessageIds.length > 0 && (
                <Receipt
                  messageIds={chapter.evidenceMessageIds}
                  getMessagesByIds={getMessagesByIds}
                  label="View Chapter Receipts"
                  explanation={`Evidence supporting Chapter ${idx + 1}`}
                />
              )}
            </article>
          </FadeReveal>
        ))}

        {!isUnlocked && story.chapters.length > 1 && (
          <div className="story-locked-teaser">
            <p>+{story.chapters.length - 1} more chapters locked in the full archive.</p>
          </div>
        )}
      </div>
    </section>
  );
}
